### ISSUE TITLE
Does not support UTF-8 characters

### ISSUE THREAD

**Issue by ostinelli** [uu59/phpass-ruby#1]
``` ruby
# encoding: utf-8
require 'phpass'

password = "pässørd"
phpass = Phpass.new(8)

password_digest = "$P$Bb/iWY7RbqXpO0zN/oZZPbKz9p/w93."
phpass.check(password, password_digest)
```

This will blow up on the `phpass.check` line:

```
/Users/roberto/.rvm/gems/ruby-2.2.2@beehive/gems/phpass-ruby-0.1.2/lib/phpass/md5.rb:43:in `crypt': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
    from /Users/roberto/.rvm/gems/ruby-2.2.2@beehive/gems/phpass-ruby-0.1.2/lib/phpass/md5.rb:21:in `check'
    from /Users/roberto/.rvm/gems/ruby-2.2.2@beehive/gems/phpass-ruby-0.1.2/lib/phpass.rb:20:in `check'
```

**Comment by ostinelli** [comment]
Just saw this is fixed by @shinyscorpion here:
https://github.com/shinyscorpion/phpass-ruby/commit/2bc4281e1771ba9e4bd1ac0e3fc9da4b8829fe7b

Maybe a pull request would be interesting?
